//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCsWebAdmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class admission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admission()
        {
            this.lettres = new HashSet<lettre>();
        }
    
        public int id_admission { get; set; }
        public string type { get; set; }
        public int id_session { get; set; }
        public System.DateTime date_cre { get; set; }
        public string choix1 { get; set; }
        public string regime1 { get; set; }
        public string choix2 { get; set; }
        public string regime2 { get; set; }
        public string choix3 { get; set; }
        public string regime3 { get; set; }
        public int id_candidat { get; set; }
        public System.DateTime date_soumettre { get; set; }
        public string etat { get; set; }
        public string motif_annulation { get; set; }
        public string desc_annulation { get; set; }
        public System.DateTime date_annulation { get; set; }
        public string chemin_lettre { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lettre> lettres { get; set; }
    }
}
