//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCsWebAdmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class lettrerecommandation
    {
        public int ID { get; set; }
        public Nullable<int> IDCandidat { get; set; }
        public Nullable<int> IDAdmission { get; set; }
        public string NomProfesseur { get; set; }
        public string PrenomProfesseur { get; set; }
        public string Organisation { get; set; }
        public string PosteOccupe { get; set; }
        public string TelephoneProfesseur { get; set; }
        public string CourrielProfesseur { get; set; }
        public byte[] Cv { get; set; }
    
        public virtual candidat candidat { get; set; }
        public virtual demandeadmission demandeadmission { get; set; }
    }
}
