//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCsWebAdmission
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGACEntitiesFl : DbContext
    {
        public SGACEntitiesFl()
            : base("name=SGACEntitiesFl")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<candidat> candidats { get; set; }
        public virtual DbSet<cour> cours { get; set; }
        public virtual DbSet<demandeadmission> demandeadmissions { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<etudiant> etudiants { get; set; }
        public virtual DbSet<laisonCP> laisonCPs { get; set; }
        public virtual DbSet<lettre> lettres { get; set; }
        public virtual DbSet<lettrerecommandation> lettrerecommandations { get; set; }
        public virtual DbSet<NivEtude> NivEtudes { get; set; }
        public virtual DbSet<programme> programmes { get; set; }
        public virtual DbSet<regime> regimes { get; set; }
        public virtual DbSet<session> sessions { get; set; }
    }
}
