//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCsWebAdmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public int id_utilisateur { get; set; }
        public string codePermanent { get; set; }
        public int id_candidat { get; set; }
        public string nip { get; set; }
        public string type { get; set; }
    
        public virtual candidat candidat { get; set; }
    }
}
