//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCsWebAdmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class demandeadmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public demandeadmission()
        {
            this.documents = new HashSet<document>();
            this.lettrerecommandations = new HashSet<lettrerecommandation>();
            this.regimes = new HashSet<regime>();
        }
    
        public int id { get; set; }
        public Nullable<int> IDCandidat { get; set; }
        public Nullable<int> IDSession { get; set; }
        public Nullable<int> IDNivEtud { get; set; }
        public string TypeDemande { get; set; }
        public string Statut { get; set; }
        public Nullable<System.DateTime> DateSousmission { get; set; }
    
        public virtual candidat candidat { get; set; }
        public virtual NivEtude NivEtude { get; set; }
        public virtual session session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lettrerecommandation> lettrerecommandations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regime> regimes { get; set; }
    }
}
